const Sequelize=require('sequelize')
const db = require("../database/db")
module.exports=db.sequelize.define(
    'users',
    {
        id:{
            type:Sequelize.INTEGER,
            primaryKey:true,
            autoIncrement:true,
         },
         user_name:{
            type:Sequelize.STRING
        },
        mobile_number:
          {
           type:Sequelize.STRING 
         },
         email_id:{
          type:Sequelize.STRING
         },
         password:{
             type:Sequelize.STRING
         },
         created:{
             type:Sequelize.DATE,
             defaultValue:Sequelize.NOW
         }
    },{
        timestamps:false
    }
)
